### ISSUE TITLE
Server not starting on java -jar target/dt-6a27c88-dirty.jar configurations/default/env.yml configurations/default/server.yml

### ISSUE THREAD

**Issue by WaliedA** [conveyal/datatools-server#11]
when runing last command 

java -jar target/dt-6a27c88-dirty.jar configurations/default/env.yml configurations/default/server.yml

it stops here

ubuntu@ip-172-31-3-112:~/datatools-server$ java -jar target/dt-6a27c88-dirty.jar configurations/default/env.yml configurations/default/server.yml
15:06:07.311 [main] INFO  c.c.datatools.manager.DataManager - Loading env.yml: configurations/default/env.yml
15:06:07.314 [main] INFO  c.c.datatools.manager.DataManager - Loading server.yml: configurations/default/server.yml
15:06:07.418 [main] INFO  c.c.d.manager.persistence.DataStore - /home/ubuntu/datatools-server/data/mapdb/projects
15:06:07.569 [main] WARN  c.c.datatools.manager.DataManager - Config property application.data.gtfs_s3_bucket not found
15:06:07.569 [main] WARN  c.c.datatools.manager.DataManager - Config property application.data.gtfs_s3_bucket not found
15:06:07.571 [main] WARN  c.c.datatools.manager.DataManager - Config property application.data.s3_credentials_file not found
15:06:07.572 [main] WARN  c.c.datatools.manager.DataManager - Config property application.data.s3_credentials_file not found
15:06:07.572 [main] INFO  c.c.datatools.manager.DataManager - Initializing gtfs cache locally (no s3 bucket) /home/ubuntu/datatools-server/data/gtfs
log4j:WARN No appenders could be found for logger (com.amazonaws.AmazonWebServiceClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
15:06:08.324 [main] INFO  com.conveyal.gtfs.GTFSCache - No bucket specified; GTFS Cache will run locally
15:06:08.495 [Thread-1] INFO  org.eclipse.jetty.util.log - Logging initialized @1736ms
15:06:08.637 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - == Spark has ignited ...
15:06:08.638 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4000
15:06:08.641 [Thread-1] INFO  org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
15:06:08.749 [Thread-1] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@9fa409b{HTTP/1.1,[http/1.1]}{0.0.0.0:4000}
15:06:08.750 [Thread-1] INFO  org.eclipse.jetty.server.Server - Started @1999ms
15:06:08.955 [main] WARN  c.c.d.m.c.api.GtfsApiController - No extension provided for GTFS API
15:06:08.967 [pool-1-thread-1] INFO  c.c.d.manager.jobs.FeedUpdater - Fetching feeds...
15:06:08.968 [pool-1-thread-1] INFO  c.c.d.manager.jobs.FeedUpdater - Current eTag list {}
15:06:08.976 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.gtfsplus.enabled not found
15:06:08.976 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.gtfsplus.enabled not found
15:06:08.976 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.gtfsplus.enabled not found
15:06:08.990 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.dump.enabled not found
15:06:08.991 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.dump.enabled not found
15:06:08.991 [main] WARN  c.c.datatools.manager.DataManager - Config property modules.dump.enabled not found
15:06:08.993 [main] WARN  c.c.datatools.manager.DataManager - Config property extensions.mtc.enabled not found
15:06:08.994 [main] WARN  c.c.datatools.manager.DataManager - Config property extensions.mtc.enabled not found
15:06:08.994 [main] WARN  c.c.datatools.manager.DataManager - Config property extensions.mtc.enabled not found
15:06:08.999 [main] INFO  c.c.datatools.manager.DataManager - Registering TransitLand Resource
15:06:09.000 [main] INFO  c.c.datatools.manager.DataManager - Registering TransitFeeds Resource

**Comment by l-vincent-l** [comment]
Please, use this repository : https://github.com/catalogueglobal/datatools-server/

**Comment by WaliedA** [comment]
OK, rectified
